# fly.toml app configuration file generated for perah-properties-vertx on 2026-06-08T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "perah-properties-vertx"
primary_region = "us-west"

[build]
  image = "ghcr.io/peter-d-kim/perah-properties-vertx:latest"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
